### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by dssecret** [tqk-gh/aircrack-ng-gui#1]
When running `aircrack-ng-gui` on my computer I get `SyntaxError: invalid Syntax`. This error originates from `File "aircrack-ng-gui.py", line 231`. I am running this on a RPI3B+.

**Comment by t-gitt** [comment]
It seems you are running it on Python 2
It's written in Python 3 so you would need to upgrade your python version
To know what python version you have, type `python --version`
